### ISSUE TITLE
Release 7.0.6 contains wrong '-SNAPSHOT' dependency

### ISSUE THREAD

**Issue by ralphlange** [epics-base/epicsCoreJava#101]
When using the auto-generated `.tar.gz` of the source files (last asset on the [release page](https://github.com/epics-base/epicsCoreJava/releases/tag/7.0.6)), the POM of `gpclient.javafx` refers to the gpclient parent POM in its `1.0.3-SNAPSHOT` version, which

- is conceptionally wrong (releases should not contain dependencies to `-SNAPSHOT` versions) and 
- does not match the parent POM one directory above (which provides version `1.0.3`).

**Comment by shroffk** [comment]
I think this might be tied to the backward compatibility with jdk8
The javafx module is excluded from the release due to missing javafx pieces in jdk8...however it still gets packaged.

I will be more aware of this in the next release however I have a feeling we will have to bite the bullet and start making releases of the libraries using jdk11 to compile them

**Comment by ralphlange** [comment]
???!
I am doing CODAC Core System packaging, i.e. complete rebuild from sources. That's why I can't use the distribution tar, but go for the tagged sources. The javafx module is being built if you do that, and I have not seen any hint that it shouldn't.

We are using jdk11 for about a year now... but again, I am repackaging from source so I don't really care how the binary packages are created that I don't use.

**Comment by ralphlange** [comment]
For me this is mainly an annoyance: it's the third patch file that I have to apply whenever I update EPICS Java...

I consider it a bug, as I think whatever is in that `.tar.gz` called 7.0.6 on the download page should be compilable.

**Comment by shroffk** [comment]
> We are using jdk11 for about a year now... but again, I am repackaging from source so I don't really care how the binary packages are created that I don't use.

The 7.0.6 release was built with open jdk 8, because of request to add jdk8 support... the release build with jdk8 skipped the javafx module.

If you build with open jdk 11 then the javafx module will be built, but since the release plugin skipped that module the snapshot was not updated.

Hacking the project so that it is built with java8... skipping javafx... but still including it in the release changes is a lot of work to just avoid moving to java 11. We should have a plan to move to java 11 in future releases and that would automatically resolve this bug

**Comment by ralphlange** [comment]
Current situation sounds awful, agreed.

No way to have both java8 and java11 stuff in the release?
I would push the complete java11 stuff to Maven Central etc. but try to bundle both in the download tar.

**Comment by shroffk** [comment]
Building and releasing both would be a pain.
Maybe we can start having a java8 branch with different version number 7.0.7-j8

**Comment by shroffk** [comment]
@ralphlange can I close this since we have resolved this my choosing the java11 build method

**Comment by ralphlange** [comment]
Sure. Closing.
