### ISSUE TITLE
No way to access description of Enum? 

### ISSUE THREAD

**Issue by jembishop** [epics-base/epicsCoreJava#132]
It looks like there is no way to access the `display.description` field of an Enum? This would be quite useful to have. 

https://github.com/epics-base/epicsCoreJava/blob/5b5c8434d2d36ce3e8a4e02999809982e3ed94ca/epics-vtype/vtype/src/main/java/org/epics/vtype/EnumDisplay.java#L16C8-L16C8

**Comment by kasemir** [comment]
In Channel Access, there is no "description". In PV Access, the normative type for numeric data includes a "display" info with a "description", https://docs.epics-controls.org/en/latest/pv-access/Normative-Types-Specification.html#display-t

The enum type has no "display", and also nothing else that holds a description, https://docs.epics-controls.org/en/latest/pv-access/Normative-Types-Specification.html#ntenum

Personally, I think it was a bad idea to add the description in the first place. In those few cases where it's really useful, a separate channel for "record.DESC" could fetch it, instead of adding it to every numeric value.
Now the question, I guess, is: Remove the display.description, or add a NTEnum.description? Either way requires update of normative type document, QSRV(2), and then the clients which care.

**Comment by jembishop** [comment]
I see, interesting, I hadn't realized there was no description field in the NTEnum, thanks for pointing that out. Looking at the [normative type](https://docs.epics-controls.org/en/latest/pv-access/Normative-Types-Specification.html#ntenum) spec it looks like there should be a descriptor field though?  
I can't seem to find a way to access it though [docs](https://javadoc.io/doc/org.epics/epics-pvaccess/latest/index.html) perhaps I am missing something. I am a bit confused what the semantic difference is meant to be between the "descriptor" and "description".
